- name: mangodb installation
  hosts: mongodb
  become: yes
  tasks:
    - name: copy mongodb repo
      ansible.builtin.copy:
        src: mogodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: Install mongodb
      ansible.builtin.package:
        name: mongodb-org
        state: present

    - name: Start and enable mongo db
      ansible.builtin.service:
        name: mongod
        state: started
        enable: yes

    - name: allow remote connections
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: restart mongodb
      ansible.builtin.service:
        name: mongod
        state: restarted
 